Fix PyPI installation issues 	When pip installing moudule from PyPI firstly download dist files 	extract and execute `setup.py`, but in progress it's fails with 	this error:
	Traceback (most recent call last):
		File "<string>", line 1, in <module>
		File "/private/tmp/pip-install-_d6vixsj/pync/setup.py", line 10, in <module>
    			file_contents.append(open(path).read())
	 FileNotFoundError: [Errno 2] No such file or directory:'/private/tmp/pip-install-....
	----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-...

	The reason why thats happen is very simple in `MANIFEST.in` we should add new instruction
	for including a `README.md` to distro packets

	My changes fix that problem and also should fix throubles with
	formating on pypi.org