New pync 2.0.3 (#37)
* Fix `AttributeError` on Notifier.list() call
When call list() method on TerminalNotifier it fals with this error

>>> Notifier.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pync/TerminalNotifier.py",
line 107, in list
    output = self.execute(["-list", group]).communicate()[0]
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pync/TerminalNotifier.py",
line 79, in execute
    if self.wait:
AttributeError: 'TerminalNotifier' object has no attribute 'wait'```

The reason of this behabior is simple. Notifier object was created without `wait`
 property and not inited in `notify` method.

ChangeID: https://github.com/SeTeM/pync/issues/35

* Add more classifiers

* Update pync version